### ISSUE TITLE
Can not show the colorbar

### ISSUE THREAD

**Issue by AyinMostima** [Mr-Milk/legendkit#25]

**Comment by AyinMostima** [comment]
Requirement already satisfied: legendkit in d:\miniconda3\envs\dataanalysis\lib\site-packages (0.3.4)
Requirement already satisfied: matplotlib in d:\miniconda3\envs\dataanalysis\lib\site-packages (from legendkit) (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in d:\miniconda3\envs\dataanalysis\lib\site-packages (from matplotlib->legendkit) (1.2.1)
Requirement already satisfied: cycler>=0.10 in d:\miniconda3\envs\dataanalysis\lib\site-packages (from matplotlib->legendkit) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\miniconda3\envs\dataanalysis\lib\site-packages (from matplotlib->legendkit) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\miniconda3\envs\dataanalysis\lib\site-packages (from matplotlib->legendkit) (1.4.5)
Requirement already satisfied: numpy>=1.23 in d:\miniconda3\envs\dataanalysis\lib\site-packages (from matplotlib->legendkit) (1.26.4)
Requirement already satisfied: packaging>=20.0 in d:\miniconda3\envs\dataanalysis\lib\site-packages (from matplotlib->legendkit) (24.1)
Requirement already satisfied: pillow>=8 in d:\miniconda3\envs\dataanalysis\lib\site-packages (from matplotlib->legendkit) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in d:\miniconda3\envs\dataanalysis\lib\site-packages (from matplotlib->legendkit) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in d:\miniconda3\envs\dataanalysis\lib\site-packages (from matplotlib->legendkit) (2.9.0)
Requirement already satisfied: six>=1.5 in d:\miniconda3\envs\dataanalysis\lib\site-packages (from python-dateutil>=2.7->matplotlib->legendkit) (1.16.0)

but the code and others like this can not show the colorbar:
from legendkit import colorart
from legendkit import cat_legend, vstack, hstack
_, ax = plt.subplots(figsize=(1, 3)); ax.set_axis_off()
m = np.random.randn(10, 2)
mappable = ax.pcolormesh(m, cmap="cool")
cbar = colorart(mappable, ax=ax, title="Colorart")
legend = cat_legend(**args, title="Legend")
vstack([legend, cbar], spacing=10, title="Stack Legend and Colorart",
       alignment="left", loc="out right center", frameon=False, ax=ax)
and

from legendkit import colorart
_, ax = plt.subplots()
m = np.random.randn(10, 10)
mappable = ax.pcolormesh(m, cmap="cool")
colorart(mappable, ax=ax, loc="out right center")

The marsilea bag will also have this problem。
![1724086069653](https://github.com/user-attachments/assets/bb0aa697-b320-4486-9924-556456dcd897)
![1724085987098](https://github.com/user-attachments/assets/e5b7e3eb-316e-40be-9db7-e66cd28e3256)
![1724085958683](https://github.com/user-attachments/assets/20a418a5-6d86-48b6-b627-903cccd032de)

**Comment by Mr-Milk** [comment]
This is the same issue as mentioned in Marsilea-viz/marsilea#42. This dark mode will change matplotlib styles. You can either submit an issue to the dark mode maintainer or change the styles yourself.

**Comment by AyinMostima** [comment]
> This is the same issue as mentioned in [Marsilea-viz/marsilea#42](https://github.com/Marsilea-viz/marsilea/issues/42). This dark mode will change matplotlib styles. You can either submit an issue to the dark mode maintainer or change the styles yourself.

Hi, I have found a solution. Using %matplotlib tk in Jupyter instead of %matplotlib notebook and %matplotlib inline can effectively avoid this problem.

**Comment by AyinMostima** [comment]
> [这与Marsilea-viz/marsilea#42](https://github.com/Marsilea-viz/marsilea/issues/42)中提到的问题相同。此暗模式将更改 matplotlib 样式。您可以向暗模式维护者提交问题，也可以自行更改样式。

These problems only occur when using PyCharm 2024.1.4, which is caused by DIE
